### PR TITLE
Added support for Windows under mingw

### PR DESCRIPTION
**Pull request by chubas**

### CODE REVIEW

**Comment by bleything** [comment]
Thanks! I'm reworking the platform detection code, but I'll make sure that mingw is included.

**Comment by bleything** [comment]
Can you please send me the contents of the RUBY_PLATFORM constant on your system?

**Comment by bleything** [comment]
fixed in 0065492ab4f8f6739efeaa8f63b9b354bbc25052

**Comment by chubas** [comment]
I use Windows only for midi related stuff, and unfortunately I don't havce a Windows machine at hand. If it is still useful to you, I can get those data tomorrow. Thanks for the fix

**Pull request closed without merging**
